# Wire Active Record Encryption keys from environment variables.
#
# Configuration is read from environment variables only (no hardcoded secrets,
# see CLAUDE.md). The keys are generated by `bin/rails db:encryption:init` and
# stored as ACTIVE_RECORD_ENCRYPTION_* (see docs/ENV_VARS.md). In the test
# environment we fall back to fixed, non-secret keys so the suite is hermetic
# and does not depend on a populated .env file. These test keys are intentionally
# public and must never be used to protect real data.
Rails.application.configure do
  primary_key = ENV["ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"]
  deterministic_key = ENV["ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"]
  key_derivation_salt = ENV["ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"]

  if Rails.env.test?
    primary_key ||= "test_primary_key_not_for_real_data_0001"
    deterministic_key ||= "test_deterministic_key_not_for_real_00001"
    key_derivation_salt ||= "test_key_derivation_salt_not_for_real_0001"
  end

  config.active_record.encryption.primary_key = primary_key
  config.active_record.encryption.deterministic_key = deterministic_key
  config.active_record.encryption.key_derivation_salt = key_derivation_salt
end
